# Generated by Django 3.2 on 2021-06-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210526_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fav', models.ManyToManyField(related_name='user_favs', to='login_app.User')),
            ],
        ),
    ]
